apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-dep
    pdb: drain-blocker
  name: test-dep
  namespace: drain-block
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-dep
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli
        imagePullPolicy: Always
        name: cli
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
